// app/utils/classes.ts
export const faithClasses = [
  {
    faith: "诞育",
    theme: "emerald",
    icon: "ph:flower-lotus-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "酋长",
        desc: "他们的攻击中携带着非常恐怖的致孕能力，能让敌人在受创的同时有几率怀上他们的孩子，而当他们将怀孕的敌人杀死后，尸体上的胎儿便会破体而出吞食尸体长大，变成“这个部落”的新族人，并成为他们的狂热追随者。",
      },
      { type: "法师", name: "生命贤者", desc: "" },
      {
        type: "牧师",
        name: "子嗣牧师",
        desc: "【诞育】的牧师在祝福或者治疗同伴时，往往有概率会使同伴“怀孕”。被治疗者身体内每孕育一个“新生命”，其受到的治疗效果便会增加三分。职业别称：求子观音",
      },
      { type: "刺客", name: "借诞之婴", desc: "" },
      {
        type: "猎人",
        name: "创生猎人",
        desc: "创生草籽（这是一种生命陷阱，被草籽接触到的生命体会被【诞育】的意志影响，从而开始渴望繁殖，并在体内快速孕育出背离主体意识的独立个体。）",
      },
      { type: "歌者", name: "", desc: "" },
    ],
  },
  {
    faith: "繁荣",
    theme: "green",
    icon: "ph:tree-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "德鲁伊",
        desc: "一个可以横跨多物种变换形体的尚战职业，其输出手段大多生猛，能抗能打，可谓全能。",
      },
      { type: "法师", name: "木精灵", desc: "" },
      { type: "牧师", name: "园丁", desc: "" },
      {
        type: "刺客",
        name: "荆棘之冠",
        desc: "通过头戴荆棘来增强各项属性能力。",
      },
      { type: "猎人", name: "美食家", desc: "" },
      { type: "歌者", name: "", desc: "" },
    ],
  },
  {
    faith: "死亡",
    theme: "slate",
    icon: "ph:skull-duotone",
    description: "",
    careers: [
      { type: "战士", name: "", desc: "" },
      { type: "法师", name: "死灵法师", desc: "" },
      {
        type: "牧师",
        name: "守墓人",
        desc: "吊命（既可以让治愈的光辉化作死亡的暗芒，又可以决定接受了自己治疗的目标是否可以死去。）",
      },
      {
        type: "刺客",
        name: "死亡编织者",
        desc: "死亡送葬（在“死亡领域”内召唤一柄巨大的死亡镰刀，对领域内的所有目标进行一次必中的死亡打击。）",
      },
      { type: "猎人", name: "猩红猎手", desc: "" },
      { type: "歌者", name: "撞钟人", desc: "" },
    ],
  },
  {
    faith: "污堕",
    theme: "purple",
    icon: "ph:virus-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "尖啸伯爵",
        desc: "尖啸伯爵是【污堕】阵营里最懂制造恐惧和收割恐惧的玩家，他们常以恐惧为食，不断的折磨敌人，在不当人的行径上与某些【战争】的信徒能打个旗鼓相当。而据说被恐惧母树吸收寰宇恐惧后诞下的恐魔，就是尖啸伯爵这个职业的原型。",
      },
      { type: "法师", name: "欲望主宰", desc: "欲望炮制傀儡" },
      { type: "牧师", name: "悲悯领主", desc: "" },
      { type: "刺客", name: "恶孽", desc: "" },
      { type: "猎人", name: "感官追猎者", desc: "" },
      { type: "歌者", name: "塞壬", desc: "" },
    ],
  },
  {
    faith: "腐朽",
    theme: "lime",
    icon: "ph:bone-duotone",
    description: "",
    careers: [
      { type: "战士", name: "木乃伊", desc: "守御，更注重自身防御" },
      { type: "法师", name: "瘟疫枢机", desc: "" },
      {
        type: "牧师",
        name: "凋零祭司",
        desc: "可以用自己的生命换取队友的生命，越自残伤重，队友越恢复迅猛。职业别称：换血牧",
      },
      { type: "刺客", name: "疮痍之目", desc: "" },
      { type: "猎人", name: "黄昏猎人", desc: "" },
      { type: "歌者", name: "腐烂颂唱者", desc: "" },
    ],
  },
  {
    faith: "湮灭",
    theme: "red",
    icon: "ph:meteor-duotone",
    description: "",
    careers: [
      { type: "战士", name: "清道夫", desc: "" },
      {
        type: "法师",
        name: "烬灭者",
        desc: "一个可以抛开世界规则随手抹去现实存在的职业。",
      },
      { type: "牧师", name: "焚化工", desc: "" },
      { type: "刺客", name: "寂灭使徒", desc: "" },
      {
        type: "猎人",
        name: "终焉行者",
        desc: "寂无声箭（追踪目标，标记位置，张弓搭弦，而后，再无声的送走猎物。将猎物送往就要崩毁的世界，亦或送往即将湮灭的时空。）",
      },
      { type: "歌者", name: "毁灭宣告", desc: "" },
    ],
  },
  {
    faith: "秩序",
    theme: "blue",
    icon: "ph:scales-duotone",
    description: "",
    careers: [
      { type: "战士", name: "秩序骑士", desc: "圣光长城（守御技能，护盾）" },
      { type: "法师", name: "元素法官", desc: "可以深研并掌控一种元素" },
      { type: "牧师", name: "公正官", desc: "" },
      { type: "刺客", name: "行刑官", desc: "" },
      { type: "猎人", name: "搜查官", desc: "" },
      { type: "歌者", name: "律者", desc: "" },
    ],
  },
  {
    faith: "真理",
    theme: "cyan",
    icon: "ph:book-open-text-duotone",
    description: "",
    careers: [
      { type: "战士", name: "格斗专家", desc: "" },
      {
        type: "法师",
        name: "博识学者",
        desc: "选修不同的知识学派，并以此为追求【真理】的基点，衍生出复杂且繁多的变种职业。（目前出现学派：机械，虚空）",
      },
      { type: "牧师", name: "外科医生", desc: "" },
      {
        type: "刺客",
        name: "暗杀博士",
        desc: "是所有刺客职业中最懂得传统刺杀的人，非常善于寻找敌人的弱点，从而可以在最合适的时机给予敌人最精准的暗杀。",
      },
      { type: "猎人", name: "陷阱大师", desc: "" },
      {
        type: "歌者",
        name: "博闻诗人",
        desc: "可以把技能书写成册页，随时使用。",
      },
    ],
  },
  {
    faith: "战争",
    theme: "rose",
    icon: "ph:sword-duotone",
    description: "",
    careers: [
      { type: "战士", name: "陷阵勇士", desc: "" },
      { type: "法师", name: "炼狱主教", desc: "" },
      {
        type: "牧师",
        name: "督战官",
        desc: "当有士卒不堪重负败下阵来时，督战官只需将手中的长鞭狠狠的抽在这些败军之卒的身上，便能以治疗代替伤害，让这些伤重的士兵恢复活力，重返战场。因为当督战官激活天赋后，他的伤害就变成了治疗。",
      },
      { type: "刺客", name: "隙光铁刺", desc: "" },
      { type: "猎人", name: "鹰眼斥候", desc: "" },
      { type: "歌者", name: "风暴之嗓", desc: "" },
    ],
  },
  {
    faith: "混乱",
    theme: "fuchsia",
    icon: "ph:spiral-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "异血同袍",
        desc: "在两军交战之际，我将永远是你的队友，无论你身处哪个阵营！",
      },
      { type: "法师", name: "灾祸之源", desc: "" },
      {
        type: "牧师",
        name: "理智蚀者",
        desc: "受到【混乱】的影响，理智蚀者的治疗会逐渐消融伤者的理智，直到其理智崩解，拥抱混乱，彻底疯狂。",
      },
      { type: "刺客", name: "折光析影", desc: "" },
      { type: "猎人", name: "渔夫", desc: "" },
      { type: "歌者", name: "失律琴师", desc: "" },
    ],
  },
  {
    faith: "痴愚",
    theme: "yellow",
    icon: "ph:mask-sad-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "竖壁骑士",
        desc: "可以凭空砌筑“真知高墙”，创造出让人意想不到的地理优势从而与敌人迂回斡旋。",
      },
      { type: "法师", name: "幕后戏师", desc: "" },
      { type: "牧师", name: "怯愚专家", desc: "" },
      { type: "刺客", name: "解构之眼", desc: "" },
      { type: "猎人", name: "猎愚人", desc: "" },
      {
        type: "歌者",
        name: "独奏家",
        desc: "【痴愚】赐予歌者的天赋是让被独奏家曲调影响的生命对指定目标产生赞同感。",
      },
    ],
  },
  {
    faith: "沉默",
    theme: "zinc",
    icon: "ph:microphone-slash-duotone",
    description: "",
    careers: [
      { type: "战士", name: "苦行僧", desc: "" },
      { type: "法师", name: "默剧大师", desc: "" },
      { type: "牧师", name: "守夜人", desc: "" },
      { type: "刺客", name: "偃偶师", desc: "" },
      {
        type: "猎人",
        name: "变色龙",
        desc: "一个极其善于伪装自己静待猎物的猎人。",
      },
      { 
        type: "歌者",
        name: "囚徒",
        desc: "沉默是他们的绝大多数。哪怕是以嗓子吃饭的歌者，在祂的意志指引下，也只能用锁链，代替歌声。可发出声响依旧是低分的表现，当囚徒们愈发理解祂的意志，从而愈发靠近祂的时候，这些“外物”便会被抛弃，并渐渐被“无声的嘶吼”和“寂然的呐喊”所取代。到那时，囚徒，才算得上真正的【沉默】歌者。"
      },
    ],
  },
  {
    faith: "记忆",
    theme: "indigo",
    icon: "ph:brain-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "镜中人",
        desc: "一个可以通过铭记对手招式从而快速复制对方战斗体系的“速记”职业。",
      },
      { type: "法师", name: "回忆旅者", desc: "" },
      { type: "牧师", name: "见证者", desc: "" },
      { type: "刺客", name: "旧日追猎者", desc: "" },
      {
        type: "猎人",
        name: "窥梦游侠",
        desc: "偷看他人的梦境，可以从梦中看到他人从前的记忆。但只能根据窥梦对象的视角观看，切换对象需要付出一点代价。",
      },
      {
        type: "歌者",
        name: "史学家",
        desc: "擅长记录历史，更擅长篡改历史，这是一群被历史学派称赞的史官。",
      },
    ],
  },
  {
    faith: "时间",
    theme: "violet",
    icon: "ph:hourglass-high-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "指针骑士",
        desc: "一个非常善于抓时机空档的真正timing侠。",
      },
      {
        type: "法师",
        name: "时间行者",
        desc: "时间战场（必须在整点开启它，并将战局和争端结束于另一个整点，但每一次循环都会消解我们对时间的概念！）",
      },
      {
        type: "牧师",
        name: "遗忘医生",
        desc: "【时间】对牧师职业的技能赐福有两个，一个是回溯状态，用来把身体状态回溯到上一个被记录的整点。一个是加速代谢，这个技能会大幅加速目标代谢，以时间治愈伤势或者身体负面状态。",
      },
      {
        type: "刺客",
        name: "另日刺客",
        desc: "是一个把【时间】的推演利用到极致的职业，他们可以穿梭于不同的推演未来中，在另一个时空杀死目标，而后将这推演的结果覆写到当下的时空中来。",
      },
      {
        type: "猎人",
        name: "驯风游侠",
        desc: "可以跟随自己的心意，化作一阵微风。当然，也有可能是肃杀的寒风。",
      },
      { type: "歌者", name: "吟游诗人", desc: "" },
    ],
  },
  {
    faith: "欺诈",
    theme: "pink",
    icon: "ph:cards-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "杂技演员",
        desc: "被祂赐予了超高的肢体柔韧性，能够做出各种匪夷所思的肢体动作。",
      },
      { type: "法师", name: "诡术大师", desc: "" },
      { type: "牧师", name: "小丑", desc: "用谎言治愈他人" },
      {
        type: "刺客",
        name: "受害者",
        desc: "致命回赠（可以激活特性，把自己受到的某一次伤害返还给伤害来源，所以他们杀人从不需要自己动手，全靠敌人的致命一击）",
      },
      {
        type: "猎人",
        name: "驯兽师",
        desc: "他可以与老鼠沟通，打听到人所不知的消息，也可以驯化老鼠，让鼠群为之服务。甚至还可以与他控制的老鼠互换身份，将自己变成老鼠。（也可能是其他动物）",
      },
      {
        type: "歌者",
        name: "魔术师",
        desc: "在祂的注视下这些歌者们可以将自己骗人的谎言化为一张张带有特殊效果的扑克牌。每当他们骗过一个人后，都会在手里凝结出一张扑克，但这张扑克具体有什么效果就要看魔术师有什么【欺诈】天赋了。",
      },
    ],
  },
  {
    faith: "命运",
    theme: "amber",
    icon: "ph:dice-five-duotone",
    description: "",
    careers: [
      {
        type: "战士",
        name: "今日勇士",
        desc: "被命运“随机”权柄赐福的职业，今日勇士能不能成为勇士，全看骰子的点数。",
      },
      { type: "法师", name: "编剧", desc: "改写他人的剧本影响命运的走向。" },
      {
        type: "牧师",
        name: "织命师",
        desc: "当有人在无法避免的灾难中即将重伤垂死的时候，虽然无法更改灾难轨迹，却能修补这人的命运，让他的重伤垂死变成轻伤逃生，甚至于无伤幸免。治疗的方法便是在一定程度上“提前”更改了目标受伤的命运。而嫁接命运一事，只不过是对于这“不稳定提前治疗方案”的一种补偿。当一位织命师三番五次尝试修补他人的命运却终究未能力挽狂澜时，他便可以选择亲手杀死目标并将他的命运嫁接在自己身上，让自己替代那个被命运抛弃的可怜人继续在命运的道路上多走一段路。",
      },
      {
        type: "刺客",
        name: "窃命之贼",
        desc: "专门窃取他人的命运，在【命运】的眷佑下，这些【命运】的刺客隐藏在阴影之中不断审视着众生的命运，当碰到他们感兴趣的命运时，他们便会现身窃走这些人的命运，在这段自己看中的命运中临时扮演一回剧本的主角。（暂时取代他人身份）",
      },
      {
        type: "猎人",
        name: "终末之笔",
        desc: "一个可以预见猎物“命终之地”并于此守株待兔的诡秘职业，他现身的地点往往代表着猎物命运的终点。",
      },
      {
        type: "歌者",
        name: "预言家",
        desc: "能预见一段未来，投掷的命运之骰点数越大越可能发生。",
      },
    ],
  },
];
