// app/utils/items.ts

// 自动计算权重，用于从高到低排序
const parseLevel = (level: string) => {
  const lv = level.toUpperCase();
  if (lv.includes("SSSS") || lv.includes("SSS'S") || lv.includes("SSSS"))
    return { weight: 70, group: "SSS+" };
  if (lv.includes("SSS")) return { weight: 60, group: "SSS" };
  if (lv.includes("SS")) return { weight: 50, group: "SS" };
  if (lv.includes("S")) return { weight: 40, group: "S" };
  if (lv.includes("A")) return { weight: 30, group: "A" };
  if (lv.includes("B")) return { weight: 20, group: "B" };
  if (lv.includes("C")) return { weight: 10, group: "C" };
  return { weight: 0, group: "UNKNOWN" };
};


const defaultAuthor = ["Mueo"];

export const allItems = [
  {
    name: "骨仆赎罪者子嗣之戒",
    level: "SSS'S",
    type: "道具",
    baseInfo: "从神傀具",
    firstAppear: "第551章",
    effects: [
      "特殊效果【恐惧养料】：你可以吸收周围的恐惧情绪，为它充能，每充满一份，戒指将亮起一张骇叫之面，每当有一张骇叫之面亮起时，你将略微提高对雷元素、恐惧情绪、【污堕】神力、【腐朽】神力的抗性。",
      "特殊效果【憎恨渴望】：每获得一份恐惧养料时，你将额外获得一份恐惧养料。",
      "特殊效果【鸣雷裁决】：消耗一份恐惧养料召降雷刑，诛灭敌人。若目标曾为戒指提供过恐惧养料，则雷刑必中。",
      "特殊效果【尖啸奴仆】：被【鸣雷裁决】击杀的尸体会自动转化为一只尖啸奴仆，拥有释放恐惧和腐化敌人的能力，它会听从命令追猎恐惧，亦或是返回鱼骨殿堂，将你的赞美带回给王座之上那位尊贵的大人。",
    ],
    owners: "程实",
    remark:
      "一枚由【死亡】亲自锻造的戒指，蕴含了二分之一【鸣雷】神性、四分之一带有恐惧情绪的【污堕】神性，以及四分之一【腐朽】神性，由于黏合了一“整份”神性，道具由从神遗器升格为无意识的从神傀具，再次暴露出【死亡】的取名能力。",
    authors: defaultAuthor,
  },
  {
    name: "骨仆乐乐尔之戒",
    level: "SSSs",
    type: "道具",
    baseInfo: "从神遗器（饰品/武器）",
    firstAppear: "首次出现于第66章，名字首次出现于第67章",
    effects: [
      "特殊效果【恐惧养料】：你可以吸收周围的恐惧情绪，为它充能，每充满一份，戒指将亮起一张尖啸之嘴。",
      "特殊效果【鸣雷裁决】：消耗一份恐惧养料召降雷刑，诛灭敌人。若目标曾为戒指提供过恐惧养料，则雷刑必中。",
      "特殊效果【王座下的骨仆】：你可以将一具尸体炼制成死亡骨仆，它可以将你的赞美带回给王座之上那位尊贵的大人。",
    ],
    owners: "程实",
    remark:
      "一枚由【死亡】亲自锻造的戒指，蕴含了二分之一【鸣雷】神性和四分之一带有恐惧情绪的【污堕】神性，其名字足以【死亡】是个取名鬼才",
    authors: defaultAuthor,
  },
  {
    name: "真理仪轨",
    level: "SSSS",
    type: "道具",
    baseInfo: "从神仪器",
    firstAppear: "第71章",
    effects: [
      "1.发射无源信标 (他借用博学主席会的【真理仪轨】，向虚空中投放了一百枚无源信标。)",
      "2.将物体挪移到虚空中 (并借用【真理仪轨】，将这个小镇挪移到了虚空之中！)",
      "3.在虚空中开辟空间 (不仅如此博学主席会甚至还动用了【真理仪轨】在虚空中开辟了一处空间，专门用于容纳远暮镇这个实验基地。)",
      "4.创造真理 (①【真理仪轨】有创造真理的神伟。②真知高墙是【真理仪轨】创造出的“真理”)",
    ],
    owners: "博学主席会",
    remark: "由于原文中比没有准确信息，故此处写有参考文献，本词条待补充。",
    authors: defaultAuthor,
  },
  {
    name: "忆妄之镜",
    level: "SSSS",
    type: "道具",
    baseInfo: "从神级造物",
    firstAppear: "第642章",
    effects: ["未知"],
    owners: "未知",
    remark:
      "【忆妄之镜】是“【记忆】唯一的从神级造物”。“那面位格堪比【真理仪轨】的镜子碎成了两半，一半变成了【无遗梦镜】，一半化作了另一个 SSS 级从神遗器，【彼梦我魇】。” 本词条待补充",
    authors: defaultAuthor,
  },
  {
    name: "行刑之刻",
    level: "SSS",
    type: "道具",
    baseInfo: "权杖/半神器",
    firstAppear: "第60章",
    effects: ["发出一道恐怖的雷罚"],
    owners: "大审判庭，墨秋斯，程实",
    remark:
      "一柄顶端缠绕雷霆的权杖，本物品后被【死亡】用于与【恐惧来临之时】融合，成为【骨仆乐乐尔之戒】",
    authors: defaultAuthor,
  },
  {
    name: "疮痍之赐",
    level: "SSS",
    type: "道具",
    baseInfo: "匕首/控制类半神器",
    firstAppear: "第279章",
    effects: [
      "1.腐化目标",
      "2.汲取目标的生机 (而【疮痍之赐】之所以称之为“疮痍之赐”，就是因为狄泽尔依然能够使用【腐朽】的力量去腐化目标，同时汲取对方的生机滋养自己。)",
    ],
    owners: "南宫，程实",
    remark:
      "【无翳的华冠】狄泽尔背叛到【腐朽】后，被【腐朽】杀死，其灵魂被封印在该道具中，暗中谋划复仇。因不知名原因落到罗纳斯皇室之后，被存放在坎纳尔城，在某一局中被南宫得到，并与其签订同生共死的契约。后契约被食谎之舌吃掉，该道具落入程实之手，后经【死亡】之手与【骨仆乐乐尔之戒】融合为【骨仆赎罪者子嗣之戒】 (怎么会有这么难听的名字)",
    authors: defaultAuthor,
  },
  {
    name: "无遗梦镜",
    level: "SSS",
    type: "道具",
    baseInfo: "从神遗器",
    firstAppear: "第641章",
    effects: [
      "【特殊效果】梦境覆盖【存在】 (它对记忆的采撷毫无遗漏，通过它，我可以直接找到属于某片区域的记忆，化为梦境，从而完整的覆盖在现实之上，暂时的改变【存在】，或者说扭曲【存在】。而当这片【存在】出现变化后，我又可以打破梦境，将被意外涂抹的区域恢复成它原来的模样。)",
      "【特殊效果】制造分身 (详见第 750 章)",
    ],
    owners: "秦薪",
    remark: "【忆妄之镜】分裂出的一部分，被秦薪得到，待补充。",
    authors: defaultAuthor,
  },
  {
    name: "彼梦我魇",
    level: "SSS",
    type: "道具",
    baseInfo: "从神级遗器",
    firstAppear: "第63章 今日又是普通的一天",
    effects: [
      "能够照出每一个人的暗面。将视线停留在镜面后，镜中会出现一个代表你内心深处欲望的魇影，不断蛊惑你与它交换。",
      "而当有一个镜中魇影存在时，其他的视线便不会再映照出另一个镜影。魇影不完全由使用者内心的欲望构成，也融合了一些镜子本身的认知和记忆。",
      "当你与魇影达成协议或者直接直视镜面时，你将会进入镜中世界，如果镜中已有一人存在，则会将其置换出来。",
      "镜中世界呈现为一座镜面构成的巨大迷宫，花纹与镜背以及镜框上的一致，镜壁无法被外力打破。",
      "所有照镜之人均会在镜中世界留下他们的记忆，每一份记忆都会使迷宫起始点产生一条岔路。岔路口会出现记忆所有者的记忆虚影，展示其过去记忆的片段。",
      "沿着每一条路走便可以浏览他们的记忆，但如果无法选择一条路一直走下去的话，便有可能迷失其中。",
    ],
    owners: "镜中人，杜熙光，李景明，丑角/程实",
    remark:
      "由【忆妄之镜】分裂而成，和魇影聊【源初】会宕机。魇影真身疑似为【污堕】令使德拉希尔科，现已通过置换脱离镜中世界。因此当前彼梦我魇已无法照出内心欲望，仅可用于通往【记忆】藏馆及无遗梦镜。目前镜内拥有丑角六人的记忆，因此有六条岔路，但似乎另有隐藏的第七条岔路仅对程实开放，道路镜壁之上刻着迷宫图。按下迷宫图中心的凹槽并使其凹陷后，将会落入隐藏的记忆垃圾场，即被【记忆】摒弃的记忆所在之地，随后可以通往无遗梦镜。（更多详见第1113-1116章）。手抚镜框，念出【记忆】的祷词后可以经由镜面进入【记忆】的藏馆。\n[外观描述]：一面与人等高的全身镜，花纹繁复样式古朴，镜面流转着湛蓝的光华，边缘镌刻着安眠的笑靥，背面则凸起着无数闭眼挣扎、恐惧呐喊的类人。",
    authors: defaultAuthor,
  },
  {
    name: "绽放只待枯萎",
    level: "SSS",
    type: "道具",
    baseInfo: "从神级造物",
    firstAppear: "第42章 被【繁荣】凝视的小镇",
    effects: ["被它所笼罩的地方，将一直繁荣下去，直到寿命的尽头。"],
    owners: "永绽镇（理智之塔）",
    remark:
      "一朵巨大到匪夷所思的“花朵雕像”，正完美的绽放着，向周围散发出柔和且富有生机的光芒。据程实估计有3.4层楼高。乍一看像“石雕”，仔细去看花瓣，在你视线集中的那一刻，花瓣就突然活了过来，变成清晰细腻的植物萼片，每一片花瓣纹理也不同。是【繁荣】的意志所在。",
    authors: defaultAuthor,
  },
  {
    name: "恐惧来临之时",
    level: "SSS",
    type: "道具",
    baseInfo: "从神级匕首",
    firstAppear: "46章",
    effects: [
      "这柄匕首并不需要刺入身体，它只需选定一个目标然后等待，当这个倒霉蛋心生恐惧之时，他的心脏就会被剥离敬献给【死亡】",
    ],
    owners: "",
    remark:
      "来自地底的迦楼罗国，是一件沾染了【污堕】和【死亡】双神性的半神器。",
    authors: defaultAuthor,
  },
  {
    name: "忆海浮梦",
    level: "SSS",
    type: "道具",
    baseInfo: "从神遗器（饰品/武器）",
    firstAppear: "首次出现于第138章，名称首次出现于第139章",
    effects: [
      "特殊效果【海梦的浮沫】：你可以激活戒指并开始计时，在不超过 24 小时的时间里结束计时后，计时期间内所有你留下的痕迹都不会成为他人的记忆。",
      "特殊效果【骇浪的激潮】：当一段记忆已经被铭记于忆海成为历史，且你身处这段历史之中时，你可以激活戒指并合理的改变它，期间留下的所有痕迹，都将成为新的历史。",
    ],
    owners: "",
    remark:
      "一枚由【记忆】亲自锻造的戒指，可以见证 3 次【存在】，使用任意效果 3 次之后戒指将不再【存在】。",
    authors: defaultAuthor,
  },
  {
    name: "永囚之时",
    level: "SSS",
    type: "道具",
    baseInfo: "从神遗器（戒指/饰品）",
    firstAppear: "513章",
    effects: [
      "特殊效果【时囚者的自醒】：所有因【时间】之力而造成的时间重置、回溯、循环均不会消解你对时间的概念，也不会影响你的意识和记忆。",
      "特殊效果【自醒者的呐喊】：所有因时间重置、回溯、循环而对你产生的正面效果，都会有小幅加成。",
    ],
    owners: "程实",
    remark: "一枚迸发于【时间】感慨，见证了时间闭环而诞生的戒指。",
    authors: defaultAuthor,
  },
  {
    name: "自罪者的遗恨",
    level: "SSS",
    type: "道具",
    baseInfo: "从神遗器（控制/武器）",
    firstAppear: "第407章",
    effects: [
      "特殊效果【自罪者的救赎】：你可以将自己和其他指定目标标记为“自罪者”，标记结束后，所有自罪者将被禁锢并吊起在祂遗留的怨念之中，直到信仰再次虔诚亦或被人救下。",
      "特殊效果【虔诚者的狂欢】：每当你孕育、诞下或使他人孕育、诞下一个新生儿，将获得一次免除任意目标“自罪者”标记的机会。",
      "特殊效果【渎神者的末日】：亵渎【诞育】的生命将自动获得“自罪者”标记。",
    ],
    owners: "程实，胡璇",
    remark:
      "胡璇赠予程实的道具，在【罪殖巢母】的自我忏悔中，由其蜕落的虔诚凝聚而成。",
    authors: defaultAuthor,
  },
  {
    name: "剥皮骨刀",
    level: "SS",
    type: "道具",
    baseInfo: "武器",
    firstAppear: "976章 原来他们叫传火者",
    effects: ["【死亡】ss级类神器，可以让一切复活的后手失效。"],
    owners: "杜期瑜，孙缈，程实",
    remark:
      "1.据说是这世间第一位剔骨工的趁手武器，之后便成了所有剔骨工梦寐以求的道具。\n2.【死亡】大人起名的功力还是一如既往的惊艳寰宇！",
    authors: defaultAuthor,
  },
  {
    name: "欲望唾弃者之门钥匙",
    level: "SS",
    type: "道具",
    baseInfo: "类神器",
    firstAppear: "第415章",
    effects: [
      "特殊效果【欲望唾弃之门】：你可以用一具充满欲望执念的尸体构筑一道欲望唾弃之门，并用门钥匙打开它，门的另一边是【时间】的囚笼，是真正的欲望深渊。",
      "特殊效果【欲望**】：手持门钥匙的时候，【污堕】之力对你的欲望拉扯效果降低。",
      "特殊效果【这也不是赐予，而是交易】：每当你使用一次【欲望唾弃之门】，你需要为王座上那位尊贵的大人，献上两份祭品。",
    ],
    owners: "程实",
    remark:
      "一枚以【欢欲之门】系带碎片为材料，由【死亡】亲自锻造的门钥匙，蕴含了祂对【污堕】神性的伟大理解。",
    authors: defaultAuthor,
  },
  {
    name: "蓊郁角冠",
    level: "SS",
    type: "道具",
    baseInfo: "装备",
    firstAppear: "第313章",
    effects: [
      "当你戴上这只王冠后，你的治疗效果将带有复苏属性，在治疗生机散尽的生命体时，将会令其复苏，相同效果仅在同一生命体上生效一次。",
    ],
    owners: "程实",
    remark:
      "由【繁荣】部族鹿角人族敬献的千年鹿角与不朽木锤炼打造的王冠，试炼结束后，红霖通过发放奖励的方式赠予程实",
    authors: defaultAuthor,
  },
  {
    name: "【欢欲之门】的信物：破碎系带",
    level: "SS",
    type: "道具",
    baseInfo: "信物",
    firstAppear: "第394章",
    effects: [
      "可以让持有者随时去往祂的门前，但正如祂那不曾主动邀请别人的恩主一样，祂无法强制你推开那扇门，除非持有者在自身欲望的驱使下，自己推开。",
    ],
    owners: "程实",
    remark: "【欢欲之门】阿夫洛斯给程实的信物，后被做成【欲望唾弃者之门钥匙】",
    authors: defaultAuthor,
  },
  {
    name: "追忆悼念",
    level: "SS",
    type: "道具",
    baseInfo: "消耗品/从神遗器",
    firstAppear: "第191章",
    effects: [
      "只要用它轻轻的碰一下自己，再去想自己想要抹去的回忆，它便会帮你掩盖这一切。",
    ],
    owners: "传火者",
    remark: "传火者似乎已经实现量产(玩笑话)",
    authors: defaultAuthor,
  },
  {
    name: "时光笔记【往日重现】",
    level: "SS",
    type: "道具",
    baseInfo: "消耗品",
    firstAppear: "第54章",
    effects: [
      "【特殊效果】可以将淹没于过去的某段记忆完整的展现在当下，犹如 AR 电影一般供旅客们观赏。",
      "【特殊效果】涂抹记忆的后果，将由参与的玩家承担。",
      "【特殊效果】能回到“记忆”，改变“过去”",
    ],
    owners: "杜熙光，崔鸿，李景明，程实，安铭瑜",
    remark: "最烂大街的一次（没好气）",
    authors: defaultAuthor,
  },
  {
    name: "荆棘泣礼",
    level: "SS",
    type: "道具",
    baseInfo: "类神器",
    firstAppear: "615章",
    effects: [
      "被鞭笞者会受到肉体和精神的双重伤害。",
      "特殊效果【哀鸣即是礼赞】：被荆棘泣礼鞭挞的对象只要高唱【繁荣】赞歌，此次鞭挞便不会造成精神伤害。",
      "特殊效果【繁荣亦有新生】：当鞭挞只造成血肉伤害时，少量恢复被鞭笞者的精神力。",
    ],
    owners: "程实",
    remark: "信仰【繁荣】的雨林部落用来自证虔诚的长鞭刑具",
    authors: defaultAuthor,
  },
  {
    name: "小丑替身",
    level: "SS",
    type: "道具",
    baseInfo: "替身道具",
    firstAppear: "第362章",
    effects: [
      "进入试炼前可以选择使用，使用后创造出一个与你一模一样的复制体代替你加入试炼。",
      "特殊效果【惟妙惟肖】：复制体为特殊的替身玩家身份，共享你的一切记忆、天赋、能力及道具。",
      "特殊效果【空欢喜】：替身玩家通关试炼后不能获得任何评分及奖励。",
      "特殊效果【击鼓传花】：替身玩家死亡后尸体变回小丑替身状态，等待下一个有缘人捡走。",
    ],
    owners: "墨殊，程实",
    remark: "【欺诈】赐予墨殊的道具，后由程实从墨殊手中抢走",
    authors: defaultAuthor,
  },
  {
    name: "幕戏之球",
    level: "S",
    type: "道具",
    baseInfo: "【痴愚】法师常用天赋(消耗品)。",
    firstAppear: "第462章 胡哥，你果然还是忘不掉那个牧师",
    effects: [
      "收集一场剧目暂存在幕戏之球中，当场景重现时，其中储存的能力便会释放，从而达到攻击/防御的效果。",
    ],
    owners: "莫离，程实",
    remark:
      "1.混沌纪元的文明孤塔通过研究【湮灭】之种发明出幕戏之球。（643章）\n2.存在各种等级（存疑，原文中表达过程实手中的两颗是s级）（462章）\n3.程实的两颗“幕戏之球”分别记录了大审判庭元素法官们引水灌城的攻城之战和自然联盟西南雨林部落中的祈福之祀，均为s级幕戏之球。（462章）\n4.由于低分段玩家没有足够的能力收集一场盛大的剧目，所以在低分段被认为为最无用的天赋，已经“沦为”随身空间，比如吃上一顿不如手指面包的饭。（462章）",
    authors: defaultAuthor,
  },
  {
    name: "凶死罗盘",
    level: "S",
    type: "道具",
    baseInfo: "【死亡】S级圣器",
    firstAppear: "第943章 瘟疫枢机",
    effects: [
      "一只巴掌大小的白骨罗盘，可以发现与凶手相似的死亡气息，从而为持有者指明凶手方位。",
    ],
    owners: "椿、椿的猩红猎手朋友",
    remark:
      "后人一定对那位大人的伟大取名艺术有所曲解，这东西明明叫“碎骨寻踪者之罗盘”！",
    authors: defaultAuthor,
  },
  {
    name: "忆海鉴知",
    level: "S",
    type: "道具",
    baseInfo: "消耗品",
    firstAppear: "第585章 交个朋友",
    effects: [
      "一柄两指长一指宽的精致木头小锤，能给予你有关所在时空的历史启示。",
    ],
    owners: "李景明，程实",
    remark:
      "龙王总是这么阔绰，谁会不喜欢跟他交换记忆呢！古来龙族爱珠宝，这下怕不是碰上真龙王了。",
    authors: defaultAuthor,
  },
  {
    name: "往逝者手骨之胸针",
    level: "S",
    type: "道具",
    baseInfo: "圣器（饰品/武器）",
    firstAppear: "第98章",
    effects: [
      "特殊效果【逝者回忆】：你可以与一具死亡不超过 12 小时的尸体对话，它将按照生前记忆如实回答你的第一个问题。",
      "特殊效果【这不是赐予，而是交易】：每当你使用一次【逝者回忆】，你需要为王座上那位尊贵的大人，献上一份祭品。",
    ],
    owners: "程实",
    remark:
      "一枚由【死亡】亲自锻造的胸针，蕴含了祂对【记忆】某些权柄的伟大理解。",
    authors: defaultAuthor,
  },
  {
    name: "降世默偶",
    level: "S",
    type: "道具",
    baseInfo: "消耗型S级圣器",
    firstAppear: "1149章 蚊子腿也是肉",
    effects: [
      "特殊效果【终归于寂】：当你摔碎它的时候，它可以为你沉默周围的一切，若使用者非【沉默】信徒，则使用者自己也无法规避该效果。",
    ],
    owners: "陈述→程实",
    remark:
      "以陈述个人的“虔诚”向【沉默】哔哔赖赖换来的赐予。诸神愚戏版“The world”，好评！",
    authors: defaultAuthor,
  },
  {
    name: "愚戏之唇",
    level: "S",
    type: "道具",
    baseInfo: "器官（融合类）",
    firstAppear: "第15章",
    effects: [
      "拥有自我意识，知道一些诸神的密辛，关键时刻有奇效",
      "“它喜欢说谎，无论你喜不喜欢；它喜欢骗人，也包括你。”",
      "“程实很早就发现【愚戏之唇】喜欢读书，尤其是在只有他一个人的时候。”——第 67 章",
    ],
    owners: "程实",
    remark:
      "一个极其神秘的道具，与程实共同组成了“【欺诈】的令使【愚戏】”，真实身份不知",
    authors: defaultAuthor,
  },
  {
    name: "食谎之舌",
    level: "S",
    type: "道具",
    baseInfo: "契约型圣器",
    firstAppear: "294章",
    effects: [
      "你可以用它立誓来玩一场真心话的游戏，参与者无数量限制，被它圈定的人需要依次问下一位一个问题，谁说了假话，谁便会被它......咳咳，‘抚摸’一下脸颊。当然，力道上或许并没有那么轻柔......",
    ],
    owners: "龙井 → 甄奕 → 程实",
    remark:
      "它确实是一个活物，而且需要进食，但只需每天喂它一个谎言，它便能够健康快乐的存活下去。",
    authors: defaultAuthor,
  },
  {
    name: "无愧假面",
    level: "S",
    type: "道具",
    baseInfo: "众生假面之一",
    firstAppear: "93章",
    effects: [
      "当你戴上这只假面的时候，你的战意将一往无前；当你消耗这只假面进行防御术法时，所有防御效果及有效时间均翻倍。",
    ],
    owners: "程实 → 崔秋实",
    remark: "“你自己的东西，你居然不知道是干什么用的？”",
    authors: defaultAuthor,
  },
  {
    name: "欢愉假面",
    level: "S",
    type: "道具",
    baseInfo: "众生假面之一",
    firstAppear: "33章",
    effects: [
      "当你带上这只假面的时候，你的心情会强制转变为欢愉；当你消耗这只假面进行召唤术法时，你的召唤物将替换为给予你这只假面的个体",
    ],
    owners: "程实 → 方诗晴",
    remark: "这是一张笑容灿烂的金色面具，分量很足",
    authors: defaultAuthor,
  },
  {
    name: "新生的洗礼",
    level: "S",
    type: "道具",
    baseInfo: "克制/道具",
    firstAppear: "第267章",
    effects: [
      "将其沾水，然后点洒在自己身上，【繁荣】的意志便会洗去【腐朽】的衰颓",
    ],
    owners: "红霖",
    remark: "专门克制【腐朽】的道具",
    authors: defaultAuthor,
  },
  {
    name: "命运之骰-既定",
    level: "S",
    type: "道具",
    baseInfo: "祷告道具",
    firstAppear: "第4章",
    effects: ["对其祷告之后，可以获得信仰的力量"],
    owners: "程实",
    remark: "程实专有的祷告道具，【命运】的既定，恒定只能投出 1 点",
    authors: defaultAuthor,
  },
  {
    name: "熔火之棺",
    level: "S",
    type: "道具",
    baseInfo: "圣器（储物）",
    firstAppear: "第775章",
    effects: [
      "特殊效果【屈于烈焰】：此空间能且仅能收容一具无意识的血肉躯壳，存放其他物品将被烈焰焚尽，存放活人将被灼尽意识。",
    ],
    owners: "谢阳、程实",
    remark: "战争烈火所烧炼出的血中余碳，熔破的空间恰好能收容一具尸体。",
    authors: defaultAuthor,
  },
  {
    name: "去时倒影",
    level: "S",
    type: "道具",
    baseInfo: "S级圣器，【记忆】道具",
    firstAppear: "第585章 交个朋友",
    effects: ["这是一根似有若无的朦胧丝线，能让你留下过去的影子"],
    owners: "龙王，程实",
    remark:
      "龙王以去时倒影和另外1个S级道具，1个SS级道具作为程实的消佣金、赔偿和慰问金",
    authors: defaultAuthor,
  },
  {
    name: "律文",
    level: "A",
    type: "道具",
    baseInfo: "消耗品",
    firstAppear: "第576章 这里关着谁？",
    effects: [
      "可免除吟诵瞬发三次持续5秒的律令传唱远方",
      "特殊效果【律令传唱远方】：通过唱诵审判之歌颁布临时律法。",
    ],
    owners: "龙王，程实",
    remark: "A级道具能做到5秒的S级天赋效果，在A级中也算是顶流了。",
    authors: defaultAuthor,
  },
  {
    name: "众生假面",
    level: "S/A/B/C",
    type: "道具",
    baseInfo: "消耗品/武器，存在各种等级",
    firstAppear: "第15章",
    effects: ["根据不同人在试炼中的表现（？）和其职业（？），拥有不同的效果"],
    owners: "程实，崔秋实，方诗晴",
    remark:
      "命运弃誓天赋带来的特殊道具，程实本人并不知道其具体作用。目前的已知假面：【吐槽假面】(B)、【疑惑假面】(A)、【报恩假面】(A)、【满足假面】(S)、【欲望假面】(B)、【庆幸假面】(A)、【厌弃假面】(B) 等。",
    authors: defaultAuthor,
  },
  {
    name: "诸神阴影之门",
    level: "A",
    type: "道具",
    baseInfo: "消耗品（一次性）",
    firstAppear: "第12章",
    effects: [
      "将任意物品投入到阴影位面中去，不限大小，不限地点，不限时间，不受控制。",
    ],
    owners: "宋亚文",
    remark:
      "这可不是什么普通货，只能在1600分段以上的天梯奖励中刷出来，而且出货率极低。",
    authors: defaultAuthor,
  },
  {
    name: "盾剑",
    level: "A",
    type: "道具",
    baseInfo: "武器",
    firstAppear: "第3章",
    effects: ["盾剑是一种可以随意转化形态的武器，可以在盾与剑之间互相转化。"],
    owners: "陈冲",
    remark:
      "这是天梯1600以上才能刷出来的A级道具，陈冲的盾剑攻防一体，对光幕性防御技能有特殊加成。",
    authors: defaultAuthor,
  },
  {
    name: "偃偶之握",
    level: "A",
    type: "道具",
    baseInfo: "道具",
    firstAppear: "第361章",
    effects: [
      "出自于混沌纪元末期【文明孤塔】对【沉默】刺客偃偶师的研究，戴上它你便可以用虚假的控偶丝线凭空迟滞对手。",
    ],
    owners: "天蝎，程实",
    remark: "一个A级换了一条命。",
    authors: defaultAuthor,
  },
  {
    name: "繁荣叶脉",
    level: "A",
    type: "道具",
    baseInfo: "消耗品",
    firstAppear: "第246章 试炼通关，重获新生！",
    effects: ["可以熔炼到装备之中，让装备更有韧性。"],
    owners: "李执，程实",
    remark:
      "一片流转着翠绿光芒的叶子。李执为了交换同心匕首所拿出的交换物。可以算是A级道具中最顶尖的存在。",
    authors: defaultAuthor,
  },
  {
    name: "冰河裂谷蜥的脚趾",
    level: "A",
    type: "道具",
    baseInfo: "风味食品（消耗品）",
    firstAppear: "第98章 鸡肋的登神之路月末结算",
    effects: ["口感偏硬，味道丰富，有提神功效，可入药。"],
    owners: "程实",
    remark: "一股酸菜的味道，也许能搭配其他食物？",
    authors: defaultAuthor,
  },
  {
    name: "信仰滴管",
    level: "A",
    type: "道具",
    baseInfo: "真理信仰道具",
    firstAppear: "第98章 鸡肋的登神之路月末结算",
    effects: [
      "可以汲取目标信仰，并为其他目标注入信仰，被注入的信仰将覆盖原有信仰，持续2小时。",
    ],
    owners: "",
    remark: "【真理】的道具总是充满了科研的味道。",
    authors: defaultAuthor,
  },
  {
    name: "往日的繁荣",
    level: "A",
    type: "道具",
    baseInfo: "治愈药剂（消耗品）",
    firstAppear: "第 15 章",
    effects: ["于记忆中遍寻，追溯并恢复到过往最鼎盛的状态。"],
    owners: "程实、胡为",
    remark:
      "在某次试炼中，由胡为带领着程实与另外四人击杀了药店老板，从而得到的药剂，有趣的是，当局试炼的任务是［保护药店老板］",
    authors: defaultAuthor,
  },
  {
    name: "自然归乡契约",
    level: "A",
    type: "道具",
    baseInfo: "契约",
    firstAppear: "615章",
    effects: [
      "可以让使用者在一定时间内化作一株植物，回归自然，植物无法移动却能拥有一定范围内的全局视野。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "树灵仪祷契约",
    level: "A",
    type: "道具",
    baseInfo: "契约",
    firstAppear: "615章",
    effects: ["可以让使用者将一株树木契约为树灵，共享它的部分视野。"],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "承恶之鳞",
    level: "B",
    type: "道具",
    baseInfo: "消耗品（存疑）",
    firstAppear: "第361章 夜半惊魂，来自清道夫的袭击",
    effects: ["将该鳞片贴在敌人身上，可以让对方受到的伤害加重三成。"],
    owners: "高崖",
    remark:
      "一枚发着微微蓝光的鳞片。“我要是能接触到敌人，早把他头都拧下来了，还需要这个？对面又没有1.3个头给我拧。”",
    authors: defaultAuthor,
  },
  {
    name: "寻声蝶",
    level: "B",
    type: "道具",
    baseInfo: "希望之洲B级生物",
    firstAppear: "第224章 瑟琉斯",
    effects: [
      "扇动翅膀时挥洒的亮晶粉末会将它看到的画面复现在半空中，又因为这种蝴蝶喜欢寻声音而飞，通常被用于压制性战场的侦查和索敌。",
    ],
    owners: "李一",
    remark: "寻声而飞，随声而落。",
    authors: defaultAuthor,
  },
  {
    name: "哑口无言",
    level: "B",
    type: "道具",
    baseInfo: "【沉默】药剂（消耗品）",
    firstAppear: "第827章 耶诺力",
    effects: [
      "喝下半瓶可以强制噤声，喝下一瓶可以消除生命体发出的一切声音，喝下三瓶，可以将生命体直接硬化为无言的木偶。但时限极短，只能持续30秒。",
    ],
    owners: "艾思，程实，张祭祖",
    remark: "我是程实，我拿两瓶。",
    authors: defaultAuthor,
  },
  {
    name: "未知道具#0001",
    level: "B",
    type: "道具",
    baseInfo: "【时间】道具",
    firstAppear: "第589章 入梦",
    effects: ["试炼结束之前会高歌一曲赞美【时间】的颂歌，声音可传到梦境之中。"],
    owners: "李景明，程实，红霖",
    remark: "一动不动的小木鸟，可以用来报时，被程实称为“报时木鸟”。",
    authors: defaultAuthor,
  },
  {
    name: "大审判庭迷你法锤玩具",
    level: "C",
    type: "道具",
    baseInfo: "玩具",
    firstAppear: "615章",
    effects: [],
    owners: "",
    remark: "质地柔软都不能用来敲核桃。",
    authors: defaultAuthor,
  },
  {
    name: "普通话机",
    level: "C",
    type: "道具",
    baseInfo: "通讯工具",
    firstAppear: "第333章 她变成了一只密林斑豹",
    effects: [
      "只需把话筒放在耳边念出目标的真名，如果目标也有相同的话机，那就可以拨打电话过去，在对方接听后可以进行通话。",
    ],
    owners:
      "程实，红霖，甄欣/奕，李景明，安铭瑜，胡璇，王某，陶怡，张祭祖（存疑）",
    remark:
      "这普通话机说是话机，但其实只是个断了线的电话筒，既没有按键，也没有交互功能。\n（619 章）“是，不然我想不出你亲自过来却不打电话的理由。...”\n（809 章）不错，王某有了一个话机...",
    authors: defaultAuthor,
  },
  {
    name: "手指面包",
    level: "C",
    type: "道具",
    baseInfo: "食物",
    firstAppear: "第1章",
    effects: [
      "形状跟人的手指一模一样，甚至连触感都做到了毫无区别。",
      "只有在入口的时候品尝到手指里爆开的蔓越莓果酱味道，才能确认这东西真的只是一种食物，而不是一根被砍断的手指。",
    ],
    owners: "程实(实际上所有玩家应该都持有)",
    remark:
      "面包如蜡，果酱很酸，C 级食品并不好吃。但这些都不妨碍它能提供能量，而提供能量就意味着，它可以续命。",
    authors: defaultAuthor,
  },
  {
    name: "罐装粘液饮料",
    level: "C",
    type: "道具",
    baseInfo: "饮料",
    firstAppear: "第1章",
    effects: ["解渴的好东西，而且因为过于粘稠，甚至还有些果腹的效果。"],
    owners: "程实等所有玩家也许都拥有过",
    remark:
      "“鼻涕水”是这种饮料的外号，触手粘液颜色发绿，粘稠至极，像极了风热感冒时流的鼻涕，故此得名。",
    authors: defaultAuthor,
  },
  {
    name: "蕈足人的感谢信",
    level: "C",
    type: "道具",
    baseInfo: "一封信",
    firstAppear: "第333章 她变成了一只密林斑豹",
    effects: ["能用来看，关键你还看不懂"],
    owners: "程实",
    remark:
      "一片树叶上有很多须根写的文字，上面书写了蕈足人最伟大的秘密：菌根缠绕三圈以上，在站立交配时可有效防止侧摔，提高生育率。（嘴哥说的你管他是不是真的）",
    authors: defaultAuthor,
  },

  // ==========================================
  // ================ 天赋档案 ================
  // ==========================================
  {
    name: "忆中故我",
    level: "SSS",
    type: "天赋",
    baseInfo: "【记忆】信仰天赋，主动",
    firstAppear: "第87章 原来你是.......，以及血与火的解脱",
    effects: ["可以让人回到过去，找到自己。"],
    owners: "",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "虚无的倒影",
    level: "SSS",
    type: "天赋",
    baseInfo: "【虚无】信仰天赋",
    firstAppear: "第257章 重回【欺诈】！【虚无】的倒影！",
    effects: [
      "与自己的影子同根同源共轭相生，可以通过互换身份来切换信仰，切换信仰后原信仰天赋效果消失。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "我就是你",
    level: "SS",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋，主动",
    firstAppear: "第128章 嘻～你怎么知道是我的？",
    effects: [
      "将目标藏起消失于众人视野，就可以直接变成目标并进行完美代替的伪装。",
    ],
    owners: "甄奕",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "无中生有的幻梦",
    level: "SS",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋，主动",
    firstAppear: "第128章 嘻～你怎么知道是我的？",
    effects: [
      "使用者可以凭借自己的想象布下幻景，当被骗对象逐渐开始相信时，这幻景里的每一个虚幻的东西都会变成真实。",
    ],
    owners: "甄奕",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "欺弱子嗣",
    level: "SS",
    type: "天赋",
    baseInfo: "【诞育】信仰天赋，被动",
    firstAppear: "第112章 胡璇，诞下了，……",
    effects: [
      "在多胞的孕育中，总会出现一个天赋最高的新生儿，它将掠夺其他新生儿的养料，吞噬他们的天赋，对“父亲”能力的继承更像是增加了新生儿对其信仰和天赋的感悟，并不是真正的继承能力，可以看作是提高了体质强度。而“母亲”则不然，新生儿一定会继承母亲的信仰和天赋。",
    ],
    owners: "胡璇",
    remark: "我生我自己？",
    authors: defaultAuthor,
  },
  {
    name: "命运织机",
    level: "SS",
    type: "天赋",
    baseInfo: "【命运】信仰天赋，主动",
    firstAppear: "第198章 原来【命运】早已定下......",
    effects: [
      "当你将一张【众生假面】扣合于面时，你的基础职业将会暂时替换为此【众生假面】来源信徒的基础职业，摘下时此【众生假面】消失。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "真理未明",
    level: "SS",
    type: "天赋",
    baseInfo: "【真理】弃誓天赋",
    firstAppear: "第190章",
    effects: [
      "急躁是埋葬真理的愚行,学者仍是学者,但已不再行走在真理的道路上,因此你可以保留祂的赐福,却再也无法得到祂的注视。",
    ],
    owners: "季月",
    remark: "“失败？不,我成功了。” “成功？不,我失败了。”",
    authors: defaultAuthor,
  },
  {
    name: "混乱扮演法",
    level: "SS",
    type: "天赋",
    baseInfo: "混乱信仰天赋，主动",
    firstAppear: "第598章 【欺诈】融合【混乱】：失去理智的小丑！",
    effects: [
      "当你在扮演某个目标时，无论他人是否对你扮演的身份表示认可，你都可以向他人展现出你想要对其展现的形象、气质和声音，以达到以假乱真的效果。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "谎如昨日",
    level: "SS",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋,主动",
    firstAppear: "第15章 试炼提前结算了",
    effects: ["你的信仰将会暂时替换为最近一个被你所欺骗信徒的信仰。"],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "往日重现",
    level: "SS",
    type: "天赋",
    baseInfo: "【记忆】信仰天赋,主动",
    firstAppear: "第54章 此地,禁止内讧！",
    effects: [
      "将淹没于过去的某段记忆完整的展现在当下,犹如AR电影一般供旅客们观赏。",
    ],
    owners: "杜熙光",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "浑水摸鱼",
    level: "S",
    type: "天赋",
    baseInfo: "混乱信仰天赋，主动",
    firstAppear: "第598章 【欺诈】融合【混乱】：失去理智的小丑！",
    effects: ["在任何种类的烟雾中，你都将获得全局视野并可化身烟雾融入其中。"],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "命运小丑",
    level: "S",
    type: "天赋",
    baseInfo: "欺诈弃誓天赋，被动",
    firstAppear: "第257章 重回【欺诈】！【虚无】的倒影！",
    effects: [
      "被命运眷顾的小丑依然是小丑，滑稽的表演同样惹人发笑。因此，你仍受祂的眷顾，享有欺骗大师的赐福，此天赋不可被其他天赋替换。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "秩序号角",
    level: "S",
    type: "天赋",
    baseInfo: "混沌信仰天赋，主动",
    firstAppear: "第598章 【欺诈】融合【混乱】：失去理智的小丑！",
    effects: [
      "你可以做出任意动作制造声响并使其等同为吹响秩序的号角，以此来抽离目标心中的无序，解除目标身上一切【混乱】状态。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "时间自有来途",
    level: "S",
    type: "天赋",
    baseInfo: "时间信仰天赋，主动",
    firstAppear: "第733章 【命运】融合【时间】，被时间遗忘的织命师！",
    effects: [
      "每当你发动命运亦有歧途后，在命运彻底走向崩坏前，你可以通过回溯时光回到歧途产生之前，以此效果产生的回溯将让天赋命运亦有歧途进入长时间冷却。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "难以捉摸的筹码",
    level: "S",
    type: "天赋",
    baseInfo: "时间信仰天赋，主动",
    firstAppear: "第733章 【命运】融合【时间】，被时间遗忘的织命师！",
    effects: [
      "每当你发动永不遗落的赌具时，骰子的可交换位置将不仅限于其当下所在位置还将包括其在过去和未来中的轨迹，时间节点的长短将依据精神力决定。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "时间推演法",
    level: "SS",
    type: "天赋",
    baseInfo: "时间信仰天赋，主动",
    firstAppear: "第733章 【命运】融合【时间】，被时间遗忘的织命师！",
    effects: [
      "每个生命都渴望时间的真相，但真相往往隐藏在众生看不见的地方，当你发动此天赋前需要选定唯一目标，发动时你将与目标在另一条时间线上的投影获得短暂的交流机会，相同效果仅在同一目标上生效一次。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "染色瘟疫",
    level: "S",
    type: "天赋",
    baseInfo: "【腐朽】法师专属天赋，主动",
    firstAppear: "第260章 新的试炼：星火将熄【繁荣】",
    effects: [
      "在天赋发动之前可以先与某个元素产生共鸣，将瘟疫的类型改变为特定元素，而后再将天赋发动，创造一个不断散发染色瘟疫的瘟疫之源。当瘟疫之源落下的时候，整片土地便会成为瘟疫的摇篮，无差别的侵蚀着踏入其中的生命体，直至所有目标拥抱【腐朽】，腐烂殆尽。",
    ],
    owners: "",
    remark: "AOE之王必备天赋。",
    authors: defaultAuthor,
  },
  {
    name: "曲调里的肖像画",
    level: "S",
    type: "天赋",
    baseInfo: "歌者职业天赋，主动",
    firstAppear: "第103章 是的，他们要一个孩子",
    effects: [
      "读取人体内各种生理曲调的变化，为目标画像。接触的诸如心跳频率、血流速度、呼吸间隔之类的“曲调”越多，天赋持有者对目标的画像就越准确。这种准确不只是记录，更是拓展和弥补，只要知道的够多，甚至能看透人的性格，猜出他们的抉择和行动。",
    ],
    owners: "秦朝歌",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "命运亦有歧途",
    level: "S",
    type: "天赋",
    baseInfo: "【命运】信仰天赋，主动",
    firstAppear: "第198章 原来【命运】早已定下......",
    effects: [
      "当你推测不久后的未来即将走向不幸时，你可以放弃当前的命运，并承受一段更加不幸的命运。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "以小博大的千术",
    level: "S",
    type: "天赋",
    baseInfo: "【命运】信仰天赋，被动",
    firstAppear: "第198章 原来【命运】早已定下......",
    effects: ["你掷出的所有1点等同于骰面最大点。"],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "永不遗落的赌具",
    level: "S",
    type: "天赋",
    baseInfo: "【命运】信仰天赋，主动",
    firstAppear: "第198章 原来【命运】早已定下......",
    effects: ["你可以跟你扔出的任何骰子交换位置。"],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "诚实小丑",
    level: "S",
    type: "天赋",
    baseInfo: "【欺诈】弃誓诅咒，被动",
    firstAppear: "第198章 原来【命运】早已定下......",
    effects: [
      "不会说谎的小丑动作拘谨，只能用廉价的真诚来博取他人的掌声。因此，你在说谎时会动作紧张破绽百出，此天赋不可被其他天赋替换。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "秩序的微光",
    level: "S",
    type: "天赋",
    baseInfo: "【秩序】信仰天赋,主动",
    firstAppear: "第52章 底牌",
    effects: [
      "在一定范围内,当目标与你遵守相同的秩序时,目标可以与你保持相同的身体状态,此状态可对目标隐藏。",
    ],
    owners: "方觉",
    remark: "还好我是个好人",
    authors: defaultAuthor,
  },
  {
    name: "律令传唱远方",
    level: "S",
    type: "天赋",
    baseInfo: "【秩序】信仰天赋,主动",
    firstAppear: "第28章/正式登场于第44章",
    effects: [
      "所有【秩序】的信徒都可以通过唱诵相应的“审判歌谣”来使自己“临时颁布”的法律生效。",
    ],
    owners: "",
    remark:
      "律者是【秩序】的歌者,他们在唱起歌谣时还能施加额外的效果,所以这个天赋对他们而言尤其好用。\n咏唱的审判歌谣类似：此地禁止XX",
    authors: defaultAuthor,
  },
  {
    name: "欺骗大师",
    level: "S",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋,被动",
    firstAppear: "第15章 试炼提前结算了",
    effects: [
      "你的谎言更容易被他人相信,除非被欺骗的目标出现认知矛盾,否则无法发现你的欺骗手段,并且你可以察觉除你之外的所有欺骗手段。",
    ],
    owners: "程实，甄奕",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "献往虚无的祭品",
    level: "S",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋,主动",
    firstAppear: "第15章 试炼提前结算了",
    effects: ["当你编造的物品并不存在却被他人广泛承认存在时,物品存在。"],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "众生相",
    level: "S",
    type: "天赋",
    baseInfo: "【命运】弃誓天赋",
    firstAppear: "第15章 试炼提前结算了",
    effects: [
      "特殊试炼奖励将替换为特殊道具【众生假面】,且此天赋不可被其他天赋替换。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "共沐神恩",
    level: "S",
    type: "天赋",
    baseInfo: "牧师职业天赋,主动",
    firstAppear: "第8章 S级天赋：共沐神恩",
    effects: [
      "治疗同属物种时会产生治疗传递效果,每多一个目标,治疗效果和治疗范围扩大一分。",
    ],
    owners: "程实",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "动人的心弦",
    level: "S",
    type: "天赋",
    baseInfo: "歌者职业天赋,主动",
    firstAppear: "第25章 方诗晴的邀请：【我们】！",
    effects: [
      "可以听到每个人心声所奏响的乐章，能模糊的感受到对方的意愿和倾向，以此来区分善恶。",
    ],
    owners: "方诗晴",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "共貌同心",
    level: "S",
    type: "天赋",
    baseInfo: "【混乱】信仰天赋,主动",
    firstAppear: "第31章 黄波之死,以及最终之门",
    effects: ["将自身形象转化为目标形象,且双方同生共死。"],
    owners: "黄波",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "回忆流光",
    level: "S",
    type: "天赋",
    baseInfo: "【时间】法师专属天赋,主动",
    firstAppear: "第45章 沉默是今晚的康桥",
    effects: [
      "以旅行者的身份穿梭于目标的记忆片段中,不断寻找自己感兴趣的场景和画面,宛如一次快速的旅行。",
    ],
    owners: "杜熙光",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "未知天赋#0001",
    level: "S",
    type: "天赋",
    baseInfo: "S级天赋，【污堕】信仰天赋",
    firstAppear: "第23章 舞狮的矮人们",
    effects: [
      "可以具化异性对自身的占有欲,细致的感知到Ta们对自身每一寸肌肤的觊觎。",
    ],
    owners: "百灵",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "虚实夹缝中的蜃景",
    level: "S",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋，被动",
    firstAppear: "第72章 在狂风暴雨中转移",
    effects: [
      "当有人轻信了他的谎言时，他所描述的一切，都会被那个人所看到。而如果有人识破了他的谎言，那他所说的一切，都不会被识破之人看到。",
    ],
    owners: "苏益达",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "永恒牢狱",
    level: "S",
    type: "天赋",
    baseInfo: "【时间】法师天赋，主动",
    firstAppear: "第30章 名侦探程实",
    effects: ["让某人停滞在时间中。"],
    owners: "",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "表情关注者",
    level: "A",
    type: "天赋",
    baseInfo: "【欺诈】信仰天赋，被动",
    firstAppear: "第98章 鸡肋的月末登神之路结算",
    effects: [
      "在你的视野中，所有表情的变动都逃不过你的注意，哪怕它只出现在你的余光里。",
    ],
    owners: "暂无",
    remark: "别动，我看见你笑了。",
    authors: defaultAuthor,
  },
  {
    name: "医人医己",
    level: "A",
    type: "天赋",
    baseInfo: "牧师职业天赋，被动",
    firstAppear: "第98章 鸡肋的月末登神之路结算",
    effects: ["你施放的治疗生效时，自己额外享受100%的治疗效果。"],
    owners: "暂无",
    remark: "自己给自己治疗，是不是200%的治疗效果？",
    authors: defaultAuthor,
  },
  {
    name: "城下的坚守",
    level: "A",
    type: "天赋",
    baseInfo: "【秩序】战士专属天赋,被动",
    firstAppear: "第16章 劫后余生",
    effects: ["使用护盾类技能时,所有防御类效果提高25%。"],
    owners: "陈冲",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "手指钥匙",
    level: "A",
    type: "天赋",
    baseInfo: "刺客职业天赋,主动",
    firstAppear: "第21章 我知道你在装傻",
    effects: ["将手指变化为任意钥匙的形状。"],
    owners: "阿铭",
    remark: "",
    authors: defaultAuthor,
  },
  {
    name: "欲望傀儡",
    level: "A",
    type: "天赋",
    baseInfo: "【污堕】信仰天赋,主动",
    firstAppear: "第24章 每个人都有自由的XP",
    effects: [
      "需要持续施法,可以将人内心深处最原始的欲念渴望释放出来,让目标变成一具只知道沉沦欲念的行尸走肉。目标会不断的沉沦在过去的欲望记忆中不可自拔,直到死去。",
    ],
    owners: "未知",
    remark: "",
    authors: defaultAuthor,
  },
].map((item) => ({ ...item, ...parseLevel(item.level) }));
